// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: server.proto
// Protobuf C++ Version: 5.27.2

#include "../../proto/server.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ReceivedEmailsList::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : emails_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReceivedEmailsList::ReceivedEmailsList(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ReceivedEmailsListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReceivedEmailsListDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReceivedEmailsListDefaultTypeInternal() {}
  union {
    ReceivedEmailsList _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReceivedEmailsListDefaultTypeInternal _ReceivedEmailsList_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR PutReply::PutReply(::_pbi::ConstantInitialized) {}
struct PutReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PutReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PutReplyDefaultTypeInternal() {}
  union {
    PutReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PutReplyDefaultTypeInternal _PutReply_default_instance_;

inline constexpr PutArgs::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : row_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        column_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PutArgs::PutArgs(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PutArgsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PutArgsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PutArgsDefaultTypeInternal() {}
  union {
    PutArgs _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PutArgsDefaultTypeInternal _PutArgs_default_instance_;

inline constexpr GetReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetReply::GetReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GetReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetReplyDefaultTypeInternal() {}
  union {
    GetReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetReplyDefaultTypeInternal _GetReply_default_instance_;

inline constexpr GetArgs::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : row_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        column_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetArgs::GetArgs(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GetArgsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetArgsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetArgsDefaultTypeInternal() {}
  union {
    GetArgs _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetArgsDefaultTypeInternal _GetArgs_default_instance_;

inline constexpr EmailObject::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : mail_from_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR EmailObject::EmailObject(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct EmailObjectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmailObjectDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmailObjectDefaultTypeInternal() {}
  union {
    EmailObject _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmailObjectDefaultTypeInternal _EmailObject_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR DelReply::DelReply(::_pbi::ConstantInitialized) {}
struct DelReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DelReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DelReplyDefaultTypeInternal() {}
  union {
    DelReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DelReplyDefaultTypeInternal _DelReply_default_instance_;

inline constexpr DelArgs::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : row_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        column_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DelArgs::DelArgs(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DelArgsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DelArgsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DelArgsDefaultTypeInternal() {}
  union {
    DelArgs _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DelArgsDefaultTypeInternal _DelArgs_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR CPutReply::CPutReply(::_pbi::ConstantInitialized) {}
struct CPutReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CPutReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CPutReplyDefaultTypeInternal() {}
  union {
    CPutReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CPutReplyDefaultTypeInternal _CPutReply_default_instance_;

inline constexpr CPutArgs::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : row_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        column_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value1_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value2_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CPutArgs::CPutArgs(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CPutArgsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CPutArgsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CPutArgsDefaultTypeInternal() {}
  union {
    CPutArgs _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CPutArgsDefaultTypeInternal _CPutArgs_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_server_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_server_2eproto = nullptr;
const ::uint32_t
    TableStruct_server_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::PutArgs, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::PutArgs, _impl_.row_),
        PROTOBUF_FIELD_OFFSET(::PutArgs, _impl_.column_),
        PROTOBUF_FIELD_OFFSET(::PutArgs, _impl_.value_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::PutReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GetArgs, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GetArgs, _impl_.row_),
        PROTOBUF_FIELD_OFFSET(::GetArgs, _impl_.column_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GetReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GetReply, _impl_.value_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::CPutArgs, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::CPutArgs, _impl_.row_),
        PROTOBUF_FIELD_OFFSET(::CPutArgs, _impl_.column_),
        PROTOBUF_FIELD_OFFSET(::CPutArgs, _impl_.value1_),
        PROTOBUF_FIELD_OFFSET(::CPutArgs, _impl_.value2_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::CPutReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::DelArgs, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::DelArgs, _impl_.row_),
        PROTOBUF_FIELD_OFFSET(::DelArgs, _impl_.column_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::DelReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::EmailObject, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::EmailObject, _impl_.mail_from_),
        PROTOBUF_FIELD_OFFSET(::EmailObject, _impl_.data_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ReceivedEmailsList, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ReceivedEmailsList, _impl_.emails_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::PutArgs)},
        {11, -1, -1, sizeof(::PutReply)},
        {19, -1, -1, sizeof(::GetArgs)},
        {29, -1, -1, sizeof(::GetReply)},
        {38, -1, -1, sizeof(::CPutArgs)},
        {50, -1, -1, sizeof(::CPutReply)},
        {58, -1, -1, sizeof(::DelArgs)},
        {68, -1, -1, sizeof(::DelReply)},
        {76, -1, -1, sizeof(::EmailObject)},
        {86, -1, -1, sizeof(::ReceivedEmailsList)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_PutArgs_default_instance_._instance,
    &::_PutReply_default_instance_._instance,
    &::_GetArgs_default_instance_._instance,
    &::_GetReply_default_instance_._instance,
    &::_CPutArgs_default_instance_._instance,
    &::_CPutReply_default_instance_._instance,
    &::_DelArgs_default_instance_._instance,
    &::_DelReply_default_instance_._instance,
    &::_EmailObject_default_instance_._instance,
    &::_ReceivedEmailsList_default_instance_._instance,
};
const char descriptor_table_protodef_server_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014server.proto\"5\n\007PutArgs\022\013\n\003Row\030\001 \001(\t\022\016"
    "\n\006Column\030\002 \001(\t\022\r\n\005Value\030\003 \001(\t\"\n\n\010PutRepl"
    "y\"&\n\007GetArgs\022\013\n\003Row\030\001 \001(\t\022\016\n\006Column\030\002 \001("
    "\t\"\031\n\010GetReply\022\r\n\005Value\030\001 \001(\t\"G\n\010CPutArgs"
    "\022\013\n\003Row\030\001 \001(\t\022\016\n\006Column\030\002 \001(\t\022\016\n\006Value1\030"
    "\003 \001(\t\022\016\n\006Value2\030\004 \001(\t\"\013\n\tCPutReply\"&\n\007De"
    "lArgs\022\013\n\003Row\030\001 \001(\t\022\016\n\006Column\030\002 \001(\t\"\n\n\010De"
    "lReply\".\n\013EmailObject\022\021\n\tmail_from\030\001 \001(\t"
    "\022\014\n\004data\030\002 \001(\t\"$\n\022ReceivedEmailsList\022\016\n\006"
    "emails\030\001 \003(\t2\203\001\n\006Server\022\034\n\003Put\022\010.PutArgs"
    "\032\t.PutReply\"\000\022\034\n\003Get\022\010.GetArgs\032\t.GetRepl"
    "y\"\000\022\037\n\004CPut\022\t.CPutArgs\032\n.CPutReply\"\000\022\034\n\003"
    "Del\022\010.DelArgs\032\t.DelReply\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_server_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_server_2eproto = {
    false,
    false,
    514,
    descriptor_table_protodef_server_2eproto,
    "server.proto",
    &descriptor_table_server_2eproto_once,
    nullptr,
    0,
    10,
    schemas,
    file_default_instances,
    TableStruct_server_2eproto::offsets,
    file_level_enum_descriptors_server_2eproto,
    file_level_service_descriptors_server_2eproto,
};
// ===================================================================

class PutArgs::_Internal {
 public:
};

PutArgs::PutArgs(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PutArgs)
}
inline PROTOBUF_NDEBUG_INLINE PutArgs::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::PutArgs& from_msg)
      : row_(arena, from.row_),
        column_(arena, from.column_),
        value_(arena, from.value_),
        _cached_size_{0} {}

PutArgs::PutArgs(
    ::google::protobuf::Arena* arena,
    const PutArgs& from)
    : ::google::protobuf::Message(arena) {
  PutArgs* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:PutArgs)
}
inline PROTOBUF_NDEBUG_INLINE PutArgs::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : row_(arena),
        column_(arena),
        value_(arena),
        _cached_size_{0} {}

inline void PutArgs::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PutArgs::~PutArgs() {
  // @@protoc_insertion_point(destructor:PutArgs)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PutArgs::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.row_.Destroy();
  _impl_.column_.Destroy();
  _impl_.value_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
PutArgs::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(PutArgs, _impl_._cached_size_),
              false,
          },
          &PutArgs::MergeImpl,
          &PutArgs::kDescriptorMethods,
          &descriptor_table_server_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 30, 2> PutArgs::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PutArgs_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::PutArgs>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string Row = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PutArgs, _impl_.row_)}},
    // string Column = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PutArgs, _impl_.column_)}},
    // string Value = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(PutArgs, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string Row = 1;
    {PROTOBUF_FIELD_OFFSET(PutArgs, _impl_.row_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string Column = 2;
    {PROTOBUF_FIELD_OFFSET(PutArgs, _impl_.column_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string Value = 3;
    {PROTOBUF_FIELD_OFFSET(PutArgs, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\7\3\6\5\0\0\0\0"
    "PutArgs"
    "Row"
    "Column"
    "Value"
  }},
};

PROTOBUF_NOINLINE void PutArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:PutArgs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.row_.ClearToEmpty();
  _impl_.column_.ClearToEmpty();
  _impl_.value_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* PutArgs::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PutArgs)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string Row = 1;
  if (!this->_internal_row().empty()) {
    const std::string& _s = this->_internal_row();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PutArgs.Row");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string Column = 2;
  if (!this->_internal_column().empty()) {
    const std::string& _s = this->_internal_column();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PutArgs.Column");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string Value = 3;
  if (!this->_internal_value().empty()) {
    const std::string& _s = this->_internal_value();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PutArgs.Value");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PutArgs)
  return target;
}

::size_t PutArgs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PutArgs)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string Row = 1;
  if (!this->_internal_row().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_row());
  }

  // string Column = 2;
  if (!this->_internal_column().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_column());
  }

  // string Value = 3;
  if (!this->_internal_value().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void PutArgs::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PutArgs*>(&to_msg);
  auto& from = static_cast<const PutArgs&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PutArgs)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_row().empty()) {
    _this->_internal_set_row(from._internal_row());
  }
  if (!from._internal_column().empty()) {
    _this->_internal_set_column(from._internal_column());
  }
  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PutArgs::CopyFrom(const PutArgs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PutArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PutArgs::InternalSwap(PutArgs* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.row_, &other->_impl_.row_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.column_, &other->_impl_.column_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
}

::google::protobuf::Metadata PutArgs::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PutReply::_Internal {
 public:
};

PutReply::PutReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:PutReply)
}
PutReply::PutReply(
    ::google::protobuf::Arena* arena,
    const PutReply& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  PutReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:PutReply)
}

const ::google::protobuf::MessageLite::ClassData*
PutReply::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(PutReply, _impl_._cached_size_),
              false,
          },
          &PutReply::MergeImpl,
          &PutReply::kDescriptorMethods,
          &descriptor_table_server_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> PutReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PutReply_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::PutReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};









::google::protobuf::Metadata PutReply::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetArgs::_Internal {
 public:
};

GetArgs::GetArgs(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GetArgs)
}
inline PROTOBUF_NDEBUG_INLINE GetArgs::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GetArgs& from_msg)
      : row_(arena, from.row_),
        column_(arena, from.column_),
        _cached_size_{0} {}

GetArgs::GetArgs(
    ::google::protobuf::Arena* arena,
    const GetArgs& from)
    : ::google::protobuf::Message(arena) {
  GetArgs* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:GetArgs)
}
inline PROTOBUF_NDEBUG_INLINE GetArgs::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : row_(arena),
        column_(arena),
        _cached_size_{0} {}

inline void GetArgs::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetArgs::~GetArgs() {
  // @@protoc_insertion_point(destructor:GetArgs)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetArgs::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.row_.Destroy();
  _impl_.column_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
GetArgs::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(GetArgs, _impl_._cached_size_),
              false,
          },
          &GetArgs::MergeImpl,
          &GetArgs::kDescriptorMethods,
          &descriptor_table_server_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 25, 2> GetArgs::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GetArgs_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GetArgs>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string Column = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(GetArgs, _impl_.column_)}},
    // string Row = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetArgs, _impl_.row_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string Row = 1;
    {PROTOBUF_FIELD_OFFSET(GetArgs, _impl_.row_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string Column = 2;
    {PROTOBUF_FIELD_OFFSET(GetArgs, _impl_.column_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\7\3\6\0\0\0\0\0"
    "GetArgs"
    "Row"
    "Column"
  }},
};

PROTOBUF_NOINLINE void GetArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:GetArgs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.row_.ClearToEmpty();
  _impl_.column_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* GetArgs::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GetArgs)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string Row = 1;
  if (!this->_internal_row().empty()) {
    const std::string& _s = this->_internal_row();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GetArgs.Row");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string Column = 2;
  if (!this->_internal_column().empty()) {
    const std::string& _s = this->_internal_column();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GetArgs.Column");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GetArgs)
  return target;
}

::size_t GetArgs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GetArgs)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string Row = 1;
  if (!this->_internal_row().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_row());
  }

  // string Column = 2;
  if (!this->_internal_column().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_column());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void GetArgs::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetArgs*>(&to_msg);
  auto& from = static_cast<const GetArgs&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GetArgs)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_row().empty()) {
    _this->_internal_set_row(from._internal_row());
  }
  if (!from._internal_column().empty()) {
    _this->_internal_set_column(from._internal_column());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetArgs::CopyFrom(const GetArgs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GetArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetArgs::InternalSwap(GetArgs* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.row_, &other->_impl_.row_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.column_, &other->_impl_.column_, arena);
}

::google::protobuf::Metadata GetArgs::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetReply::_Internal {
 public:
};

GetReply::GetReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GetReply)
}
inline PROTOBUF_NDEBUG_INLINE GetReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GetReply& from_msg)
      : value_(arena, from.value_),
        _cached_size_{0} {}

GetReply::GetReply(
    ::google::protobuf::Arena* arena,
    const GetReply& from)
    : ::google::protobuf::Message(arena) {
  GetReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:GetReply)
}
inline PROTOBUF_NDEBUG_INLINE GetReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : value_(arena),
        _cached_size_{0} {}

inline void GetReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetReply::~GetReply() {
  // @@protoc_insertion_point(destructor:GetReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GetReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.value_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
GetReply::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(GetReply, _impl_._cached_size_),
              false,
          },
          &GetReply::MergeImpl,
          &GetReply::kDescriptorMethods,
          &descriptor_table_server_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 22, 2> GetReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GetReply_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GetReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string Value = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetReply, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string Value = 1;
    {PROTOBUF_FIELD_OFFSET(GetReply, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\10\5\0\0\0\0\0\0"
    "GetReply"
    "Value"
  }},
};

PROTOBUF_NOINLINE void GetReply::Clear() {
// @@protoc_insertion_point(message_clear_start:GetReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* GetReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GetReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string Value = 1;
  if (!this->_internal_value().empty()) {
    const std::string& _s = this->_internal_value();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GetReply.Value");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GetReply)
  return target;
}

::size_t GetReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GetReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string Value = 1;
  if (!this->_internal_value().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void GetReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetReply*>(&to_msg);
  auto& from = static_cast<const GetReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GetReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetReply::CopyFrom(const GetReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GetReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetReply::InternalSwap(GetReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
}

::google::protobuf::Metadata GetReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CPutArgs::_Internal {
 public:
};

CPutArgs::CPutArgs(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CPutArgs)
}
inline PROTOBUF_NDEBUG_INLINE CPutArgs::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::CPutArgs& from_msg)
      : row_(arena, from.row_),
        column_(arena, from.column_),
        value1_(arena, from.value1_),
        value2_(arena, from.value2_),
        _cached_size_{0} {}

CPutArgs::CPutArgs(
    ::google::protobuf::Arena* arena,
    const CPutArgs& from)
    : ::google::protobuf::Message(arena) {
  CPutArgs* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:CPutArgs)
}
inline PROTOBUF_NDEBUG_INLINE CPutArgs::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : row_(arena),
        column_(arena),
        value1_(arena),
        value2_(arena),
        _cached_size_{0} {}

inline void CPutArgs::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CPutArgs::~CPutArgs() {
  // @@protoc_insertion_point(destructor:CPutArgs)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CPutArgs::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.row_.Destroy();
  _impl_.column_.Destroy();
  _impl_.value1_.Destroy();
  _impl_.value2_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
CPutArgs::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(CPutArgs, _impl_._cached_size_),
              false,
          },
          &CPutArgs::MergeImpl,
          &CPutArgs::kDescriptorMethods,
          &descriptor_table_server_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 38, 2> CPutArgs::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CPutArgs_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CPutArgs>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string Value2 = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(CPutArgs, _impl_.value2_)}},
    // string Row = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CPutArgs, _impl_.row_)}},
    // string Column = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CPutArgs, _impl_.column_)}},
    // string Value1 = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(CPutArgs, _impl_.value1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string Row = 1;
    {PROTOBUF_FIELD_OFFSET(CPutArgs, _impl_.row_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string Column = 2;
    {PROTOBUF_FIELD_OFFSET(CPutArgs, _impl_.column_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string Value1 = 3;
    {PROTOBUF_FIELD_OFFSET(CPutArgs, _impl_.value1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string Value2 = 4;
    {PROTOBUF_FIELD_OFFSET(CPutArgs, _impl_.value2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\10\3\6\6\6\0\0\0"
    "CPutArgs"
    "Row"
    "Column"
    "Value1"
    "Value2"
  }},
};

PROTOBUF_NOINLINE void CPutArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:CPutArgs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.row_.ClearToEmpty();
  _impl_.column_.ClearToEmpty();
  _impl_.value1_.ClearToEmpty();
  _impl_.value2_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* CPutArgs::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CPutArgs)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string Row = 1;
  if (!this->_internal_row().empty()) {
    const std::string& _s = this->_internal_row();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CPutArgs.Row");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string Column = 2;
  if (!this->_internal_column().empty()) {
    const std::string& _s = this->_internal_column();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CPutArgs.Column");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string Value1 = 3;
  if (!this->_internal_value1().empty()) {
    const std::string& _s = this->_internal_value1();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CPutArgs.Value1");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string Value2 = 4;
  if (!this->_internal_value2().empty()) {
    const std::string& _s = this->_internal_value2();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "CPutArgs.Value2");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CPutArgs)
  return target;
}

::size_t CPutArgs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CPutArgs)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string Row = 1;
  if (!this->_internal_row().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_row());
  }

  // string Column = 2;
  if (!this->_internal_column().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_column());
  }

  // string Value1 = 3;
  if (!this->_internal_value1().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_value1());
  }

  // string Value2 = 4;
  if (!this->_internal_value2().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_value2());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CPutArgs::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CPutArgs*>(&to_msg);
  auto& from = static_cast<const CPutArgs&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CPutArgs)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_row().empty()) {
    _this->_internal_set_row(from._internal_row());
  }
  if (!from._internal_column().empty()) {
    _this->_internal_set_column(from._internal_column());
  }
  if (!from._internal_value1().empty()) {
    _this->_internal_set_value1(from._internal_value1());
  }
  if (!from._internal_value2().empty()) {
    _this->_internal_set_value2(from._internal_value2());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CPutArgs::CopyFrom(const CPutArgs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CPutArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CPutArgs::InternalSwap(CPutArgs* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.row_, &other->_impl_.row_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.column_, &other->_impl_.column_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value1_, &other->_impl_.value1_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value2_, &other->_impl_.value2_, arena);
}

::google::protobuf::Metadata CPutArgs::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CPutReply::_Internal {
 public:
};

CPutReply::CPutReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:CPutReply)
}
CPutReply::CPutReply(
    ::google::protobuf::Arena* arena,
    const CPutReply& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  CPutReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:CPutReply)
}

const ::google::protobuf::MessageLite::ClassData*
CPutReply::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(CPutReply, _impl_._cached_size_),
              false,
          },
          &CPutReply::MergeImpl,
          &CPutReply::kDescriptorMethods,
          &descriptor_table_server_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> CPutReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CPutReply_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CPutReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};









::google::protobuf::Metadata CPutReply::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DelArgs::_Internal {
 public:
};

DelArgs::DelArgs(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DelArgs)
}
inline PROTOBUF_NDEBUG_INLINE DelArgs::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::DelArgs& from_msg)
      : row_(arena, from.row_),
        column_(arena, from.column_),
        _cached_size_{0} {}

DelArgs::DelArgs(
    ::google::protobuf::Arena* arena,
    const DelArgs& from)
    : ::google::protobuf::Message(arena) {
  DelArgs* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:DelArgs)
}
inline PROTOBUF_NDEBUG_INLINE DelArgs::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : row_(arena),
        column_(arena),
        _cached_size_{0} {}

inline void DelArgs::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
DelArgs::~DelArgs() {
  // @@protoc_insertion_point(destructor:DelArgs)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DelArgs::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.row_.Destroy();
  _impl_.column_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
DelArgs::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(DelArgs, _impl_._cached_size_),
              false,
          },
          &DelArgs::MergeImpl,
          &DelArgs::kDescriptorMethods,
          &descriptor_table_server_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 25, 2> DelArgs::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DelArgs_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DelArgs>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string Column = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(DelArgs, _impl_.column_)}},
    // string Row = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DelArgs, _impl_.row_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string Row = 1;
    {PROTOBUF_FIELD_OFFSET(DelArgs, _impl_.row_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string Column = 2;
    {PROTOBUF_FIELD_OFFSET(DelArgs, _impl_.column_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\7\3\6\0\0\0\0\0"
    "DelArgs"
    "Row"
    "Column"
  }},
};

PROTOBUF_NOINLINE void DelArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:DelArgs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.row_.ClearToEmpty();
  _impl_.column_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* DelArgs::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DelArgs)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string Row = 1;
  if (!this->_internal_row().empty()) {
    const std::string& _s = this->_internal_row();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DelArgs.Row");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string Column = 2;
  if (!this->_internal_column().empty()) {
    const std::string& _s = this->_internal_column();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DelArgs.Column");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DelArgs)
  return target;
}

::size_t DelArgs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DelArgs)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string Row = 1;
  if (!this->_internal_row().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_row());
  }

  // string Column = 2;
  if (!this->_internal_column().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_column());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void DelArgs::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DelArgs*>(&to_msg);
  auto& from = static_cast<const DelArgs&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DelArgs)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_row().empty()) {
    _this->_internal_set_row(from._internal_row());
  }
  if (!from._internal_column().empty()) {
    _this->_internal_set_column(from._internal_column());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DelArgs::CopyFrom(const DelArgs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DelArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DelArgs::InternalSwap(DelArgs* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.row_, &other->_impl_.row_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.column_, &other->_impl_.column_, arena);
}

::google::protobuf::Metadata DelArgs::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DelReply::_Internal {
 public:
};

DelReply::DelReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:DelReply)
}
DelReply::DelReply(
    ::google::protobuf::Arena* arena,
    const DelReply& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  DelReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:DelReply)
}

const ::google::protobuf::MessageLite::ClassData*
DelReply::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(DelReply, _impl_._cached_size_),
              false,
          },
          &DelReply::MergeImpl,
          &DelReply::kDescriptorMethods,
          &descriptor_table_server_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> DelReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DelReply_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DelReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};









::google::protobuf::Metadata DelReply::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EmailObject::_Internal {
 public:
};

EmailObject::EmailObject(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:EmailObject)
}
inline PROTOBUF_NDEBUG_INLINE EmailObject::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::EmailObject& from_msg)
      : mail_from_(arena, from.mail_from_),
        data_(arena, from.data_),
        _cached_size_{0} {}

EmailObject::EmailObject(
    ::google::protobuf::Arena* arena,
    const EmailObject& from)
    : ::google::protobuf::Message(arena) {
  EmailObject* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:EmailObject)
}
inline PROTOBUF_NDEBUG_INLINE EmailObject::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : mail_from_(arena),
        data_(arena),
        _cached_size_{0} {}

inline void EmailObject::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
EmailObject::~EmailObject() {
  // @@protoc_insertion_point(destructor:EmailObject)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void EmailObject::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.mail_from_.Destroy();
  _impl_.data_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
EmailObject::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(EmailObject, _impl_._cached_size_),
              false,
          },
          &EmailObject::MergeImpl,
          &EmailObject::kDescriptorMethods,
          &descriptor_table_server_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 33, 2> EmailObject::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_EmailObject_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::EmailObject>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string data = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(EmailObject, _impl_.data_)}},
    // string mail_from = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(EmailObject, _impl_.mail_from_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string mail_from = 1;
    {PROTOBUF_FIELD_OFFSET(EmailObject, _impl_.mail_from_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string data = 2;
    {PROTOBUF_FIELD_OFFSET(EmailObject, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\13\11\4\0\0\0\0\0"
    "EmailObject"
    "mail_from"
    "data"
  }},
};

PROTOBUF_NOINLINE void EmailObject::Clear() {
// @@protoc_insertion_point(message_clear_start:EmailObject)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.mail_from_.ClearToEmpty();
  _impl_.data_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* EmailObject::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:EmailObject)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string mail_from = 1;
  if (!this->_internal_mail_from().empty()) {
    const std::string& _s = this->_internal_mail_from();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "EmailObject.mail_from");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string data = 2;
  if (!this->_internal_data().empty()) {
    const std::string& _s = this->_internal_data();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "EmailObject.data");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:EmailObject)
  return target;
}

::size_t EmailObject::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:EmailObject)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string mail_from = 1;
  if (!this->_internal_mail_from().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_mail_from());
  }

  // string data = 2;
  if (!this->_internal_data().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_data());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void EmailObject::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EmailObject*>(&to_msg);
  auto& from = static_cast<const EmailObject&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:EmailObject)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_mail_from().empty()) {
    _this->_internal_set_mail_from(from._internal_mail_from());
  }
  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EmailObject::CopyFrom(const EmailObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EmailObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EmailObject::InternalSwap(EmailObject* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.mail_from_, &other->_impl_.mail_from_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
}

::google::protobuf::Metadata EmailObject::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ReceivedEmailsList::_Internal {
 public:
};

ReceivedEmailsList::ReceivedEmailsList(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ReceivedEmailsList)
}
inline PROTOBUF_NDEBUG_INLINE ReceivedEmailsList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ReceivedEmailsList& from_msg)
      : emails_{visibility, arena, from.emails_},
        _cached_size_{0} {}

ReceivedEmailsList::ReceivedEmailsList(
    ::google::protobuf::Arena* arena,
    const ReceivedEmailsList& from)
    : ::google::protobuf::Message(arena) {
  ReceivedEmailsList* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:ReceivedEmailsList)
}
inline PROTOBUF_NDEBUG_INLINE ReceivedEmailsList::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : emails_{visibility, arena},
        _cached_size_{0} {}

inline void ReceivedEmailsList::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ReceivedEmailsList::~ReceivedEmailsList() {
  // @@protoc_insertion_point(destructor:ReceivedEmailsList)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ReceivedEmailsList::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ReceivedEmailsList::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(ReceivedEmailsList, _impl_._cached_size_),
              false,
          },
          &ReceivedEmailsList::MergeImpl,
          &ReceivedEmailsList::kDescriptorMethods,
          &descriptor_table_server_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 33, 2> ReceivedEmailsList::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ReceivedEmailsList_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ReceivedEmailsList>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string emails = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ReceivedEmailsList, _impl_.emails_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string emails = 1;
    {PROTOBUF_FIELD_OFFSET(ReceivedEmailsList, _impl_.emails_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\22\6\0\0\0\0\0\0"
    "ReceivedEmailsList"
    "emails"
  }},
};

PROTOBUF_NOINLINE void ReceivedEmailsList::Clear() {
// @@protoc_insertion_point(message_clear_start:ReceivedEmailsList)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.emails_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ReceivedEmailsList::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ReceivedEmailsList)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated string emails = 1;
  for (int i = 0, n = this->_internal_emails_size(); i < n; ++i) {
    const auto& s = this->_internal_emails().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ReceivedEmailsList.emails");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ReceivedEmailsList)
  return target;
}

::size_t ReceivedEmailsList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ReceivedEmailsList)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated string emails = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_emails().size());
  for (int i = 0, n = _internal_emails().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_emails().Get(i));
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ReceivedEmailsList::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReceivedEmailsList*>(&to_msg);
  auto& from = static_cast<const ReceivedEmailsList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ReceivedEmailsList)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_emails()->MergeFrom(from._internal_emails());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReceivedEmailsList::CopyFrom(const ReceivedEmailsList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ReceivedEmailsList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReceivedEmailsList::InternalSwap(ReceivedEmailsList* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.emails_.InternalSwap(&other->_impl_.emails_);
}

::google::protobuf::Metadata ReceivedEmailsList::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_server_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
