// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: smtp.proto

#include "../../proto/smtp.pb.h"
#include "../../proto/smtp.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace smtp {

static const char* SMTPService_method_names[] = {
  "/smtp.SMTPService/SendEmail",
};

std::unique_ptr< SMTPService::Stub> SMTPService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SMTPService::Stub> stub(new SMTPService::Stub(channel, options));
  return stub;
}

SMTPService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendEmail_(SMTPService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SMTPService::Stub::SendEmail(::grpc::ClientContext* context, const ::smtp::SendEmailRequest& request, ::smtp::SendEmailResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::smtp::SendEmailRequest, ::smtp::SendEmailResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendEmail_, context, request, response);
}

void SMTPService::Stub::async::SendEmail(::grpc::ClientContext* context, const ::smtp::SendEmailRequest* request, ::smtp::SendEmailResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::smtp::SendEmailRequest, ::smtp::SendEmailResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendEmail_, context, request, response, std::move(f));
}

void SMTPService::Stub::async::SendEmail(::grpc::ClientContext* context, const ::smtp::SendEmailRequest* request, ::smtp::SendEmailResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendEmail_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::smtp::SendEmailResponse>* SMTPService::Stub::PrepareAsyncSendEmailRaw(::grpc::ClientContext* context, const ::smtp::SendEmailRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::smtp::SendEmailResponse, ::smtp::SendEmailRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendEmail_, context, request);
}

::grpc::ClientAsyncResponseReader< ::smtp::SendEmailResponse>* SMTPService::Stub::AsyncSendEmailRaw(::grpc::ClientContext* context, const ::smtp::SendEmailRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendEmailRaw(context, request, cq);
  result->StartCall();
  return result;
}

SMTPService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SMTPService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SMTPService::Service, ::smtp::SendEmailRequest, ::smtp::SendEmailResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SMTPService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::smtp::SendEmailRequest* req,
             ::smtp::SendEmailResponse* resp) {
               return service->SendEmail(ctx, req, resp);
             }, this)));
}

SMTPService::Service::~Service() {
}

::grpc::Status SMTPService::Service::SendEmail(::grpc::ServerContext* context, const ::smtp::SendEmailRequest* request, ::smtp::SendEmailResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace smtp

